### ISSUE TITLE
It does not work ! - Does not create any folder

### ISSUE THREAD

**Issue by Pava1955** [ImKyleDouglas/jellyfin_music#1]
Win 10 environment - I performed the steps described: folder selection, file extension identification (*.flac), name new folder.
Indicates how many files are present and then closes without creating the destination folder.
Where am I wrong??

**Comment by ImKyleDouglas** [comment]
I sincerely apologize for the mistake I made in the code. I overlooked the inconsistency between the key values used for FLAC files and the ones used for M4A files, which caused the program to malfunction. I have fixed the code and thoroughly tested it to ensure that everything now works perfectly. I apologize for any inconvenience caused and assure you that I will take this as a learning opportunity to improve my coding practices. Thank you for your understanding.

**Comment by Pava1955** [comment]
Hi Kyle, I re-ran the procedure you updated and this time it went a little better as it created a folder but there are no *.flac files inside!
I am sending you two images with the original file folder and the one that was created by the application.
Let me know if I do something wrong.
Greetings
![Originale](https://github.com/ImKyleDouglas/jellyfin_music/assets/135723308/38a7ea57-b2bc-497d-b42b-501c8936420d)
![Org_1](https://github.com/ImKyleDouglas/jellyfin_music/assets/135723308/11fd9b80-1221-4fa7-8923-a73971eebd9b)

**Comment by ImKyleDouglas** [comment]
I greatly appreciate your willingness to help me. Without your feedback I wouldn't have been able to do this. The problem was that the program was trying to move file paths from one drive to another. This is not possible. In order to fix this problem, I rewrote the code to copy all music files instead of cut/move. Your specific problem is fixed. If you have any problems in the future it should show up in the music error window as seen in the new readme.md. It might not look like much has changed but, the entire code base was almost entirely rewritten and it is more than twice as long as it was in the previous version. This is mostly due to the music error window. 
Again, thanks for your help and patience. Third times a charm, right?

**Comment by Pava1955** [comment]
Hi Kyle and thank you for your attention to my comments.
The latest version seems to work very well !
I only have one observation to make: when the procedure ends with the reports I can't get the *.csv or Excel file (which I think should contain all the error messages) to be generated, I also attach an image. While the "Copy Bottom" function.
Let me know how you proceed.
Thank you !
![JellyOrgMusic](https://github.com/ImKyleDouglas/jellyfin_music/assets/135723308/486b4347-c3d0-4fbe-b27c-b5988ad7d938)

**Comment by ImKyleDouglas** [comment]
This should be fixed now. I added a changelog.md that can be viewed on GitHub to track all changes from now on. Things are starting to look and feel a lot better now but, I still have a long way to go before this is finished. Thanks for your support.

**Comment by Pava1955** [comment]
Thank you. I'll proceed with the tests and keep you updated.
A greeting and good heat! (I'm in Rome in Italy and these days it's quite hot!)
